server {
    #SSL configuration
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ${DOMAIN_NAME};
    #server_name mipinhei.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;


    #protocols required
    ssl_protocols TLSv1.2 TLSv1.3;

    #root directory for WPress
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    #pass the PHP requests to wp container
    location ~ \.php$ {
        include fastcgi_params;
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}