services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    expose:
      - "${MYSQL_PORT}"
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${SUDO_USER}/data/mariadb
      o: bind

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${SUDO_USER}/data/wordpress
      o: bind
